secret_key = "It's a lonely road to the top."

[server]
bind = '0.0.0.0'
port = 8000

[db]
driver_name = "mysql"
dsn = "herui:Admin@123@tcp(172.172.177.191:3306)/onesite_dev?charset=utf8mb4&parseTime=true"
max_open_conn = 10
max_idle_conn = 5

[redis]
addr = "172.172.177.191:6379"
password = ""
db = 0

[auth]
timeout = "1h"
